## 微信推送信息
wechat:
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  wxTemplateUrl: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=

  ## 申请的测试公众号 appId 和 appSecret 注意，冒号后面有一个空格，冒号是英文的
  appId: wx550956544f1a2c96
  appSecret: 62765ab376f6e4605a8f3060291c3e54

  ## 对方的扫码id 注意，冒号后面有一个空格，冒号是英文的
  toUser: oDJ2s6SHA4V-QiXq1-VSjcL-LJUo
  ##发生的消息模板id
  templateId: fzJZfWOvilmPwO2n1M9dik5nfGsmbPW5okED8FdRa7E


## 天气
weather:
  url: https://autodev.openspeech.cn/csp/api/v2.1/weather?openId=aiuicus&clientType=android&sign=android&city=
  ## 对方的地区如：北京 注意，冒号后面有一个空格，冒号是英文的
  region: 宁德


infor:
  ## 过年日期  格式如2022-01-20
  newYearDate: 2000-01-21
  ## 恋爱日期
  loveDate: 2000-01-01
  ## 生日
  birthday: 2000-01-01

## 申请的天行api参数值
tianApi: db36b8ceece5605cf22b1b563baa6c2a
